VNASTWebsite/Controllers/AssignmentController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace VNASTWebsite.Controllers
{
    public class AssignmentController : Controller
    {
        // GET: Assignment
        public ActionResult Assignments()
        {
            try
            {
                string get_assignments = AccountController.apiRequestController.RequestGet("tasks");
                var assignments = JsonConvert.DeserializeObject<List<Models.Assignment>>(get_assignments);

                return View(assignments);
            }
            catch { }

            return View();
        }

        public ActionResult AddAssignment()
        {
            return View();
        }

        // POST: add new assigment
        [HttpPost]
        public ActionResult AddAssignment(Models.Assignment assignment)
        {
            bool update_data = AccountController.apiRequestController.AddAssignmentRequest(assignment);
            if (update_data)
            {
                return RedirectToAction("Assignments");
            }
            else
            {
                return View("Error");
            }
        }

        public ActionResult EditAssignment(string id)
        {
            string get_assignments = AccountController.apiRequestController.RequestGet("tasks");
            var assignments = JsonConvert.DeserializeObject<List<Models.Assignment>>(get_assignments);
            var assignmentToEdit = assignments.Where(s => s._id == id).FirstOrDefault();
            return View(assignmentToEdit);
        }

        // PUT: Assignment
        [HttpPost]
        public ActionResult EditAssignment(Models.Assignment assignment)
        {
            bool update_data = AccountController.apiRequestController.EditAssignmentRequest(assignment);
            if (update_data)
            {
                return RedirectToAction("Assignments");
            }
            else
            {
                return View("Error");
            }
        }

        // DELETE
        public ActionResult DeleteAssignment(string id)
        {
            bool delete_assignment = AccountController.apiRequestController.RequestDelete("tasks/" + id);
            if (delete_assignment)
            {
                return RedirectToAction("Assignments");
            }
            else
            {
                return View("Error");
            }
        }
    }
}

VNASTWebsite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - VNAST</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("VNAST", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (!Request.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("To use the system you must Login...", "About", "Home")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Tasks", "Assignments", "Assignment")</li>
                        <li>@Html.ActionLink("Chat", "Chat", "Chat")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Best Developers</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>